deploy:

  runs-on: ubuntu-latest

  name: Deploy the JAR file to the remote server

  needs: build

  steps:

    - uses: actions/checkout@v2

    - name: Set up JDK 1.8

      uses: actions/setup-java@v1

      with:

        java-version: 1.8

    - name: Generate the package

      run: mvn -B package --file pom.xml -Dmaven.test.skip=true

    - name: Deploy the package to the remote server

      uses: ajayuke/github-action-scp@release

      with:

        local: target/workflow-github-actions-1.0-SNAPSHOT.jar

        remote: ajayuke/simple-java-maven-app/actions/workflow-github-actions.jar # My remote directory

        host: ${{ secrets.HOST }}

        username: ${{ secrets.SSH_USER }}

        password: ${{ secrets.SSH_PASSWORD }}

    - name: Run a script on remote server (start the application)

      if: always()

      uses: ajayuke/ssh-action@master

      with:

        command: |

          cd ajayuke/simple-java-maven-app/actions/ && java -jar workflow-github-actions.jar &

        host: ${{ secrets.HOST }}

        user: ${{ secrets.SSH_USER }}

        pass: ${{ secrets.SSH_PASSWORD }}

        args: "-tt"

        # The & in the command runs the process on background

